#!/usr/bin/env python3
"""
QuantumVerse - Task 2.1: Geodesic Neural ODE Surrogate
Training Module

This script trains a neural network to approximate geodesic integration.
It uses a dataset generated by datagen.py and trains an MLP (256-256-256)
to predict the final event after proper time τ.

Architecture:
  Input: [initial_event(4), initial_velocity(4), tau(1), metric_params(N)] → total 9+N
  Hidden: 256-256-256 (ReLU)
  Output: final_event(4)  (t, r, θ, φ)

Loss:
  L = MSE(final_event_pred, final_event_true) + λ * L_symplectic
  where L_symplectic enforces symplectic structure preservation (optional).

Author: Kilo Code (AI Assistant)
Date: 2026-04-28
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
import h5py
import json
from pathlib import Path
from typing import Tuple, Dict, Optional
import argparse
import time
from datetime import datetime

# Device selection
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

class GeodesicDataset(Dataset):
    """PyTorch dataset for geodesic samples with multi-worker support."""
    
    def __init__(self, h5_path: Path, split: str = 'train', train_frac: float = 0.8):
        """
        Load dataset from HDF5 and split into train/val/test.
        
        Args:
            h5_path: Path to HDF5 file generated by datagen.py
            split: 'train', 'val', or 'test'
            train_frac: Fraction of data for training (rest split equally val/test)
        """
        super().__init__()
        self.h5_path = str(h5_path)  # convert to string for multiprocessing
        self.split = split
        self.train_frac = train_frac
        
        # Load indices only (not data) — this is done in main process
        with h5py.File(h5_path, 'r') as f:
            N = len(f['final_event'])
            indices = np.arange(N)
            np.random.seed(42)  # reproducible split
            np.random.shuffle(indices)
            
            n_train = int(N * train_frac)
            n_val = (N - n_train) // 2
            n_test = N - n_train - n_val
            
            if split == 'train':
                self.indices = indices[:n_train]
            elif split == 'val':
                self.indices = indices[n_train:n_train+n_val]
            else:  # test
                self.indices = indices[n_train+n_val:]
            
            self.N = len(self.indices)
        
        # Each worker will open its own HDF5 handle
        self.h5_file = None
    
    def __len__(self):
        return self.N
    
    def __getitem__(self, idx: int) -> Tuple[torch.Tensor, torch.Tensor]:
        """Get (input, output) pair. Thread-safe for multi-worker DataLoader."""
        # Open HDF5 file on first access in this worker (fork-safe)
        if self.h5_file is None:
            self.h5_file = h5py.File(self.h5_path, 'r')
        
        i = self.indices[idx]
        
        # Load arrays
        initial_event = self.h5_file['initial_event'][i]      # (4,)
        initial_velocity = self.h5_file['initial_velocity'][i]  # (4,)
        metric_params = self.h5_file['metric_params'][i]      # (N_params,)
        tau = self.h5_file['tau'][i]                          # scalar
        final_event = self.h5_file['final_event'][i]          # (4,)
        
        # Concatenate input: [event(4), velocity(4), tau(1), metric_params(N)]
        input_vec = np.concatenate([initial_event, initial_velocity, [tau], metric_params])
        input_tensor = torch.tensor(input_vec, dtype=torch.float32)
        
        # Output: final_event (4,)
        output_tensor = torch.tensor(final_event, dtype=torch.float32)
        
        return input_tensor, output_tensor

class GeodesicMLP(nn.Module):
    """Multi-layer perceptron for geodesic prediction."""
    
    def __init__(self, input_dim: int = 9, hidden_dim: int = 256, output_dim: int = 4, num_layers: int = 3):
        """
        Initialize MLP.
        
        Args:
            input_dim: Input dimension (4 event + 4 velocity + 1 tau + N params)
            hidden_dim: Hidden layer width (default 256)
            output_dim: Output dimension (4 event coords)
            num_layers: Number of hidden layers (default 3 → 256-256-256)
        """
        super().__init__()
        
        layers = []
        in_dim = input_dim
        
        for _ in range(num_layers):
            layers.append(nn.Linear(in_dim, hidden_dim))
            layers.append(nn.ReLU())
            layers.append(nn.BatchNorm1d(hidden_dim))  # stabilize training
            in_dim = hidden_dim
        
        # Output layer (no activation)
        layers.append(nn.Linear(in_dim, output_dim))
        
        self.network = nn.Sequential(*layers)
        
        # Initialize weights (Kaiming for ReLU)
        self.apply(self._init_weights)
    
    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.kaiming_normal_(m.weight, mode='fan_in', nonlinearity='relu')
            if m.bias is not None:
                nn.init.zeros_(m.bias)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Forward pass: x shape (batch, input_dim) → (batch, output_dim)."""
        return self.network(x)

def symplectic_loss(pred: torch.Tensor, true: torch.Tensor, 
                    initial_state: torch.Tensor, lambda_reg: float = 0.1) -> torch.Tensor:
    """
    Optional regularization: encourage symplectic structure preservation.
    This is a placeholder; a proper symplectic loss would involve Jacobian regularization.
    
    For now, simple L2 on velocity-like components (if we were predicting full trajectory).
    Since we only predict endpoint, symplectic loss is less direct.
    """
    # Placeholder: just return 0 for now
    return torch.tensor(0.0, device=pred.device)

def train_epoch(model: nn.Module, dataloader: DataLoader, 
                optimizer: optim.Optimizer, criterion: nn.Module,
                lambda_symplectic: float = 0.1, device: torch.device = device) -> float:
    """Train for one epoch."""
    model.train()
    total_loss = 0.0
    
    for batch_idx, (inputs, targets) in enumerate(dataloader):
        inputs, targets = inputs.to(device), targets.to(device)
        
        optimizer.zero_grad()
        predictions = model(inputs)
        
        # Main MSE loss
        mse_loss = criterion(predictions, targets)
        
        # Symplectic regularization (optional)
        # reg_loss = symplectic_loss(predictions, targets, inputs, lambda_symplectic)
        reg_loss = torch.tensor(0.0, device=device)
        
        loss = mse_loss + lambda_symplectic * reg_loss
        loss.backward()
        
        # Gradient clipping (stabilize training)
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        
        optimizer.step()
        
        total_loss += loss.item()
    
    return total_loss / len(dataloader)

def validate(model: nn.Module, dataloader: DataLoader, 
             criterion: nn.Module, device: torch.device = device) -> float:
    """Validate on held-out set."""
    model.eval()
    total_loss = 0.0
    
    with torch.no_grad():
        for inputs, targets in dataloader:
            inputs, targets = inputs.to(device), targets.to(device)
            predictions = model(inputs)
            loss = criterion(predictions, targets)
            total_loss += loss.item()
    
    return total_loss / len(dataloader)

def export_to_onnx(model: nn.Module, sample_input: torch.Tensor, onnx_path: Path):
    """Export trained model to ONNX format for C++ deployment."""
    model.eval()
    
    # Ensure sample_input is on CPU for ONNX export
    sample_input = sample_input.cpu()
    
    # Fix Windows Unicode issue: redirect stdout to avoid cp1252 encoding errors
    # from torch.onnx internal verbose prints (checkmarks, etc.)
    import sys
    import io
    old_stdout = sys.stdout
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
    
    try:
        torch.onnx.export(
            model,
            sample_input,
            str(onnx_path),
            export_params=True,
            opset_version=14,  # ONNX opset version
            do_constant_folding=True,
            input_names=['input'],
            output_names=['final_event'],
            dynamic_axes={
                'input': {0: 'batch_size'},
                'final_event': {0: 'batch_size'}
            }
        )
    finally:
        sys.stdout = old_stdout
    
    print(f"Model exported to ONNX: {onnx_path}")

def train(dataset_path: Path, output_dir: Path, resume_path: Optional[Path] = None):
    """Main training loop."""
    
    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Hyperparameters (stable configuration - proven to work)
    hparams = {
        'hidden_dim': 256,
        'num_layers': 3,
        'learning_rate': 1e-3,
        'batch_size': 128,  # Stable batch size (was 1024 - causing crashes)
        'num_epochs': 100,
        'weight_decay': 1e-5,
        'lambda_symplectic': 0.0  # disable for now
    }
    
    # Save hyperparameters
    with open(output_dir / 'hparams.json', 'w') as f:
        json.dump(hparams, f, indent=2)
    
    # Create datasets
    print("Loading datasets...")
    train_dataset = GeodesicDataset(dataset_path, split='train')
    val_dataset = GeodesicDataset(dataset_path, split='val')
    
    # DataLoader: stable configuration (num_workers=0 is reliable)
    train_loader = DataLoader(train_dataset, batch_size=hparams['batch_size'],
                              shuffle=True, num_workers=0, pin_memory=True)
    val_loader = DataLoader(val_dataset, batch_size=hparams['batch_size'],
                            shuffle=False, num_workers=0, pin_memory=True)
    
    print(f"Train samples: {len(train_dataset)}, Val samples: {len(val_dataset)}")
    
    # Determine input dimension from first sample
    sample_input, _ = train_dataset[0]
    input_dim = sample_input.shape[0]
    output_dim = 4  # final event
    
    print(f"Input dim: {input_dim}, Output dim: {output_dim}")
    
    # Create model
    model = GeodesicMLP(
        input_dim=input_dim,
        hidden_dim=hparams['hidden_dim'],
        output_dim=output_dim,
        num_layers=hparams['num_layers']
    ).to(device)
    
    # Resume from checkpoint if provided
    start_epoch = 0
    if resume_path:
        checkpoint = torch.load(resume_path, map_location=device)
        model.load_state_dict(checkpoint['model_state_dict'])
        start_epoch = checkpoint['epoch'] + 1
        print(f"Resumed from epoch {start_epoch}")
    
    # Loss and optimizer
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), 
                          lr=hparams['learning_rate'],
                          weight_decay=hparams['weight_decay'])
    
    # Learning rate scheduler (reduce on plateau)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min',
                                                     factor=0.5, patience=5)
    
    # Training loop
    print("Starting training...")
    best_val_loss = float('inf')
    
    for epoch in range(start_epoch, hparams['num_epochs']):
        start_time = time.time()
        
        train_loss = train_epoch(model, train_loader, optimizer, criterion,
                                 hparams['lambda_symplectic'], device)
        val_loss = validate(model, val_loader, criterion, device)
        
        scheduler.step(val_loss)
        
        epoch_time = time.time() - start_time
        
        print(f"Epoch {epoch+1}/{hparams['num_epochs']} | "
              f"Train: {train_loss:.6f} | Val: {val_loss:.6f} | "
              f"Time: {epoch_time:.1f}s")
        
        # Save checkpoint
        checkpoint = {
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'train_loss': train_loss,
            'val_loss': val_loss
        }
        torch.save(checkpoint, output_dir / f'checkpoint_epoch{epoch+1}.pth')
        
        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            torch.save(checkpoint, output_dir / 'best_model.pth')
            print(f"  -> New best model (val_loss={val_loss:.6f})")
    
    # Final export to ONNX
    print("Training complete. Exporting to ONNX...")
    best_checkpoint = torch.load(output_dir / 'best_model.pth', map_location=device)
    model.load_state_dict(best_checkpoint['model_state_dict'])
    
    # Create sample input for ONNX export
    sample_batch = next(iter(val_loader))[0][:1].to(device)  # 1 sample
    onnx_path = output_dir / 'geodesic_ode.onnx'
    export_to_onnx(model, sample_batch, onnx_path)
    
    # Save metadata
    metadata = {
        'train_loss': float(best_checkpoint['train_loss']),
        'val_error': float(best_checkpoint['val_loss']),
        'num_epochs': hparams['num_epochs'],
        'input_dim': int(input_dim),
        'output_dim': output_dim,
        'hidden_dim': hparams['hidden_dim'],
        'num_layers': hparams['num_layers'],
        'date_trained': datetime.now().isoformat(),
        'dataset': str(dataset_path)
    }
    with open(output_dir / 'metadata.json', 'w') as f:
        json.dump(metadata, f, indent=2)
    
    print(f"Model and metadata saved to {output_dir}")
    return str(onnx_path)

def main():
    parser = argparse.ArgumentParser(description="Train Geodesic Neural ODE")
    parser.add_argument('--dataset', type=str, required=True, help='HDF5 dataset path')
    parser.add_argument('--output-dir', type=str, default='./models/geodesic_ode',
                        help='Output directory for checkpoints and ONNX model')
    parser.add_argument('--resume', type=str, default='', help='Resume from checkpoint')
    parser.add_argument('--epochs', type=int, default=100, help='Number of epochs')
    parser.add_argument('--batch-size', type=int, default=128, help='Batch size')
    parser.add_argument('--lr', type=float, default=1e-3, help='Learning rate')
    args = parser.parse_args()
    
    dataset_path = Path(args.dataset)
    output_dir = Path(args.output_dir)
    
    # Override hparams if provided
    # (Would modify global hparams dict; omitted for brevity)
    
    onnx_path = train(dataset_path, output_dir, Path(args.resume) if args.resume else None)
    print(f"Training complete. ONNX model: {onnx_path}")

if __name__ == '__main__':
    main()