/**
 * @file AlertListener.cpp
 * @brief Implementation of the AlertListener base class
 *
 * This translation unit exists to host the Q_OBJECT meta-object code
 * generated by MOC for AlertListener.
 */

#include "AlertListener.h"

namespace quantumverse {

AlertListener::AlertListener(QObject* parent)
    : QObject(parent)
{
}

} // namespace quantumverse
